from . import payment_gateway_config
from . import res_company
from . import res_partner
from . import res_config_settings
from . import reward_config
from . import reward_distribution_rule
from . import reward_record
from . import reward_redemption
from . import product_template
from . import loyalty_history
from . import sale_order
from . import account_move
