# -*- coding: utf-8 -*-
#############################################################################
#
#    Anantam Innovision Private Limited.
#
#    Copyright (C) 2026-TODAY Anantam Innovision(<https://anantaminnovision.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

import base64
import gc
import io
import logging
import random

import requests as http_requests
from PIL import Image

from odoo import _, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}?width={width}&height={height}&seed={seed}&nologo=true"


class ProductPublicCategory(models.Model):
    _inherit = 'product.public.category'

    av_ai_icon = fields.Binary(
        string='AI Icon',
        help='64×64 icon generated by Pollinations AI from the category name.',
        attachment=True,
    )

    def _make_white_transparent(self, image_bytes):
        img = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
        data = img.getdata()
        new_data = []
        for r, g, b, a in data:
            lum = (r + g + b) / 3.0
            if lum > 180:
                new_data.append((0, 0, 0, 0))
            elif lum > 50:
                alpha = int(255 * (180 - lum) / 130.0)
                new_data.append((0, 0, 0, alpha))
            else:
                new_data.append((0, 0, 0, 255))
        img.putdata(new_data)
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()

    def _fetch_pollinations_image(self, prompt_text, width, height):
        prompt = http_requests.utils.quote(prompt_text)
        url = POLLINATIONS_URL.format(prompt=prompt, width=width, height=height, seed=random.randint(1, 999999))
        _logger.info("Pollinations request: %s", url)
        try:
            response = http_requests.get(url, timeout=60)
        except Exception as exc:
            raise UserError(_("Network error: %s") % exc)
        if response.status_code != 200:
            raise UserError(_("Pollinations returned status %s.") % response.status_code)
        if "image" not in response.headers.get("Content-Type", ""):
            raise UserError(_("Unexpected response type from Pollinations."))
        return response.content

    def action_generate_ai_icon(self):
        for category in self:
            image_b64 = self._fetch_pollinations_image(
                f"simple clean SVG style minimalist line-art icon of {category.name}, thin black strokes only, solid white background, flat 2d icon design, no shading, no colors, no text, UI icon",
                width=128, height=128,
            )
            # sudo() required: server action runs as admin to write binary field on category
            category.sudo().av_ai_icon = base64.b64encode(self._make_white_transparent(image_b64))
            del image_b64
            gc.collect()
            _logger.info("AI icon saved for category '%s'.", category.name)
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Done'),
                'message': _('AI icon generated for %d category(s).') % len(self),
                'type': 'success',
            },
        }

    # def create(self, vals):
    #     record = super().create(vals)
    #     # Skip external HTTP calls when created by WC sync — cron_generate_ai_assets
    #     # will fill in missing icons/images for all categories in the next run.
    #     if self.env.context.get('syncing_from_wc'):
    #         return record
    #     if not record.av_ai_icon:
    #         try:
    #             record.action_generate_ai_icon()
    #             _logger.info("Auto icon generation done for '%s'.", record.name)
    #         except Exception:
    #             _logger.warning("Auto icon generation failed for '%s'.", record.name, exc_info=True)
    #     if not record.image_1920:
    #         try:
    #             record.action_generate_ai_image()
    #             _logger.info("Auto image generation done for '%s'.", record.name)
    #         except Exception:
    #             _logger.warning("Auto image generation failed for '%s'.", record.name, exc_info=True)
    #     return record

    def cron_generate_ai_assets(self, batch_size=5):
        # Process one batch per cron run to avoid memory exhaustion
        # Categories missing icon — handle first
        need_icon = self.search([('parent_id', '=', False), ('av_ai_icon', '=', False)], limit=batch_size)
        for category in need_icon:
            try:
                category.action_generate_ai_icon()
                self.env.cr.commit()
                gc.collect()
            except Exception:
                self.env.cr.rollback()
                _logger.warning("Icon generation failed for '%s'.", category.name, exc_info=True)

        # Categories missing main image
        need_image = self.search([('parent_id', '=', False), ('image_1920', '=', False)], limit=batch_size)
        for category in need_image:
            try:
                category.action_generate_ai_image()
                self.env.cr.commit()
                gc.collect()
            except Exception:
                self.env.cr.rollback()
                _logger.warning("Image generation failed for '%s'.", category.name, exc_info=True)

    def action_generate_ai_image(self):
        for category in self:
            image_b64 = self._fetch_pollinations_image(
                f"{category.name} product category image, vibrant professional ecommerce photography, clean background, square composition",
                width=800, height=800,
            )
            # sudo() required: server action runs as admin to write image_1920 on category
            category.sudo().image_1920 = base64.b64encode(image_b64)
            del image_b64
            gc.collect()
            _logger.info("AI main image saved for category '%s'.", category.name)
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Done'),
                'message': _('AI image generated for %d category(s).') % len(self),
                'type': 'success',
            },
        }
