# -*- coding: utf-8 -*-
#############################################################################
#
#    Anantam Innovision Private Limited.
#
#    Copyright (C) 2026-TODAY Anantam Innovision(<https://anantaminnovision.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################

import base64
import logging
import random

import requests as http_requests

from odoo import _, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

POLLINATIONS_URL = "https://image.pollinations.ai/prompt/{prompt}?width=64&height=64&seed={seed}&nologo=true"


class ProductPublicCategory(models.Model):
    _inherit = 'product.public.category'

    av_ai_icon = fields.Binary(
        string='AI Icon',
        help='64×64 icon generated by Pollinations AI from the category name.',
        attachment=True,
    )

    def action_generate_ai_icon(self):
        for category in self:
            prompt = http_requests.utils.quote(
                f"{category.name} product category icon, flat minimal colorful design, white background"
            )
            url = POLLINATIONS_URL.format(prompt=prompt, seed=random.randint(1, 999999))
            _logger.info("Generating AI icon for category '%s' from %s", category.name, url)
            try:
                response = http_requests.get(url, timeout=60)
            except Exception as exc:
                raise UserError(_("Network error while generating icon for '%s': %s") % (category.name, exc))
            if response.status_code != 200:
                raise UserError(_("Pollinations returned status %s for '%s'.") % (response.status_code, category.name))
            content_type = response.headers.get("Content-Type", "")
            if "image" not in content_type:
                raise UserError(_("Unexpected response type '%s' for '%s'.") % (content_type, category.name))
            # sudo() required: server action runs as admin to write binary field on category
            category.sudo().av_ai_icon = base64.b64encode(response.content)
            _logger.info("AI icon saved for category '%s'.", category.name)
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Done'),
                'message': _('AI icon generated for %d category(s).') % len(self),
                'type': 'success',
            },
        }
