{
    'name': 'Aveenix Website',
    'version': '1.0',
    'category': 'Website',
    'summary': 'Modern eCommerce website - red & gold design',
    'description': 'Modern eCommerce website - red & gold design',
    'author': 'Anantam Innovision Private Limited',
    'website': 'https://anantaminnovision.com/',
    'depends': ['website', 'website_sale', 'website_crm', 'website_sale_wishlist', 'product_brand', 'account', 'aveenix_rewards'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/product_category_data.xml',
        'data/product_data.xml',
        'data/mail_template_admin_order.xml',
        'data/ir_cron_data.xml',
        'data/server_action_category_icon.xml',
        'views/website_config_views.xml',
        'views/layout.xml',
        'views/templates.xml',
        'views/affiliate_click_log_views.xml',
        'views/affiliate_cart_line_views.xml',
        'views/product_template_views.xml',
        'views/product_public_category_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'aveenix_website/static/src/css/theme.css',
            'aveenix_website/static/src/js/dark_mode.js',
            'aveenix_website/static/src/js/compare.js',
            'aveenix_website/static/src/js/wishlist_no_disable.js',
            'aveenix_website/static/src/js/shop_filters.js',
            'aveenix_website/static/src/js/cart_login_gate.js',
            'aveenix_website/static/src/js/external_images.js',
            'aveenix_website/static/src/js/affiliate_cart.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
