import os
import re
import copy

I18N_DIR = os.path.join(os.path.dirname(__file__), 'i18n')
MODULE = 'aveenix_website'
VIEWS_DIR = os.path.join(os.path.dirname(__file__), 'views')

from lxml import etree

# INLINE elements only — exact copy of Odoo's TRANSLATED_ELEMENTS in odoo/tools/translate.py
# These are treated as "translatable inline" — they can be grouped with surrounding text
# into a single msgid fragment. Block elements (div, a, p, h1...) are NOT here;
# Odoo recurses INTO them rather than treating them as one unit.
TRANSLATED_ELEMENTS = {
    'abbr', 'b', 'bdi', 'bdo', 'br', 'cite', 'code', 'data', 'del', 'dfn', 'em',
    'font', 'i', 'ins', 'kbd', 'keygen', 'mark', 'math', 'meter', 'output',
    'progress', 'q', 'ruby', 's', 'samp', 'small', 'span', 'strong', 'sub',
    'sup', 'time', 'u', 'var', 'wbr', 'text', 'select', 'option',
}
# Exact copy of Odoo's TRANSLATED_ATTRS (odoo/tools/translate.py)
TRANSLATED_ATTRS = {
    'string', 'add-label', 'help', 'sum', 'avg', 'confirm', 'placeholder', 'alt',
    'title', 'aria-label', 'aria-keyshortcuts', 'aria-placeholder',
    'aria-roledescription', 'aria-valuetext', 'value_label', 'data-tooltip',
    'label', 'confirm-label', 'confirm-title', 'cancel-label',
}
SKIPPED_ELEMENTS = {'script', 'style', 'title'}
space_re = re.compile(r'^[\s﻿]*$')

strings_ordered = []
strings_map = {}

def nonspace(text):
    return bool(text) and not space_re.fullmatch(text)

def has_directive(el):
    return any(k.startswith('t-') or k == 'groups' for k in el.attrib)

def local_tag(el):
    tag = el.tag
    if not isinstance(tag, str):
        return None
    return tag.split('}')[-1] if '}' in tag else tag

def translatable(el):
    lt = local_tag(el)
    if lt is None or lt in SKIPPED_ELEMENTS:
        return False
    if lt not in TRANSLATED_ELEMENTS:
        return False
    if has_directive(el):
        return False
    return all(translatable(c) for c in el)

def hastext(node, pos=0):
    children = list(node)
    # text before child[pos]
    prev_tail = children[pos-1].tail if pos > 0 else node.text
    if nonspace(prev_tail):
        return True
    if pos < len(children):
        c = children[pos]
        if translatable(c):
            # check attrs
            for k, v in c.attrib.items():
                if k in TRANSLATED_ATTRS and v:
                    return True
            if hastext(c, 0):
                return True
            if hastext(node, pos + 1):
                return True
    return False

def serialize_fragment(div):
    """Serialize <div>...</div> content, strip outer tag."""
    s = etree.tostring(div, method='xml', encoding='unicode')
    return s[5:-6]  # remove <div> and </div>

def add_string(s, xmlid):
    s = s.strip()
    if not s or len(s) <= 1 or s.startswith('/') or s.startswith('$'):
        return
    if s not in strings_map:
        strings_map[s] = set()
        strings_ordered.append(s)
    strings_map[s].add(xmlid)

def process_node(node, xmlid):
    """Mimic Odoo's translate_xml_node to extract the same msgids."""
    lt = local_tag(node)
    if lt is None or lt in SKIPPED_ELEMENTS:
        return
    if node.get('t-translation', '').strip() == 'off':
        return

    children = list(node)
    pos = 0
    while True:
        if hastext(node, pos):
            div = etree.Element('div')
            div.text = (children[pos-1].tail if pos > 0 else node.text) or ''
            # Collect consecutive translatable inline children WITH their tails.
            # Odoo moves elements (with tails) into a div, then strips the whole
            # content — so we preserve tails and rely on .strip() for whitespace.
            while pos < len(children) and translatable(children[pos]):
                child_copy = copy.deepcopy(children[pos])
                div.append(child_copy)
                pos += 1
            content = serialize_fragment(div)
            original = content.strip()
            if original:
                add_string(original, xmlid)
        if pos >= len(children):
            break
        # recurse into non-translatable child
        process_node(children[pos], xmlid)
        pos += 1

    # attributes
    for k, v in node.attrib.items():
        if k in TRANSLATED_ATTRS and nonspace(v):
            add_string(v.strip(), xmlid)

for fname in ['templates.xml', 'layout.xml']:
    fpath = os.path.join(VIEWS_DIR, fname)
    tree = etree.parse(fpath)
    for template in tree.getroot().iter('template'):
        tid = template.get('id', '')
        if tid:
            process_node(template, f'{MODULE}.{tid}')

strings_data = [(s, sorted(strings_map[s])) for s in strings_ordered]
print(f"Extracted {len(strings_data)} strings")

TRANSLATIONS = {
    'zh_CN': {
        'Up to 70% Off': '高达七折优惠',
        'Get the latest gadgets at unbeatable prices': '以无与伦比的价格获取最新电子产品',
        'Shop Now': '立即购买',
        'Fashion Week Special': '时装周特惠',
        'New Arrivals': '新品上市',
        'Discover the latest trends in fashion': '探索最新时尚潮流',
        'Explore': '探索',
        'Transform Your Space': '改变您的空间',
        'Beautiful furniture and decor for every room': '每个房间都有精美的家具和装饰',
        'Browse': '浏览',
        'Previous': '上一个',
        'Next': '下一个',
        'Shop by Category': '按分类购物',
        'For You': '为您推荐',
        'Best Sellers': '畅销商品',
        'View All': '查看全部',
        'Laptops': '笔记本电脑',
        'Mobile': '手机',
        'Gaming': '游戏',
        'Monitors': '显示器',
        'Headphones': '耳机',
        'Smart Home': '智能家居',
        'Trending Products': '热门商品',
        'Add to Cart': '加入购物车',
        'Why Choose Aveenix?': '为什么选择 Aveenix？',
        'Secure Payments': '安全支付',
        'Safe and secure payment methods guaranteed.': '保证安全可靠的支付方式。',
        'Fast Delivery': '快速配送',
        'Current shipping at supreme delivery speeds.': '以最快速度发货配送。',
        'Hassle Free Returns': '无忧退货',
        'Simple and easy return policy for all products.': '所有商品均有简单便捷的退货政策。',
        '24/7 Support': '全天候支持',
        'Round-the-clock customer support team.': '全天候客户支持团队。',
        'Sell on Aveenix': '在 Aveenix 上销售',
        'Reach millions of customers by becoming a seller on AVEENIX': '成为 AVEENIX 卖家，触达数百万顾客',
        'Start Selling': '开始销售',
        'Compare Products': '商品对比',
        'Back to Home': '返回首页',
        'Compare features, pricing, and specifications side-by-side': '并排比较功能、价格和规格',
        'Products to Compare': '待对比商品',
        'Total Value': '总价值',
        'In Stock': '有货',
        'On Sale': '促销中',
        'Add All to Cart': '全部加入购物车',
        'Clear Comparison': '清除对比',
        '0 items': '0 件商品',
        'Start Comparing Products': '开始对比商品',
        'Add Products': '添加商品',
        'My Favourites': '我的收藏',
        'All Items': '全部商品',
        'Toggle View': '切换视图',
        'List View': '列表视图',
        'Total Favourites': '收藏总数',
        'Clear Favourites': '清除收藏',
        'No favourites yet': '暂无收藏',
        'Add products to your favourites by clicking the heart icon on product cards': '点击商品卡片上的心形图标将商品添加到收藏',
        'Start Shopping': '开始购物',
        'My Wishlist': '我的愿望清单',
        'Total Wishlist': '愿望清单总数',
        'Clear Wishlist': '清除愿望清单',
        'Your wishlist is empty': '您的愿望清单为空',
        'Add products to your wishlist by clicking the star icon on product cards': '点击商品卡片上的星形图标将商品添加到愿望清单',
        'Contact Us': '联系我们',
        'Location': '地址',
        'Aveenix Express': 'Aveenix 快递',
        'Regional Delivery Centers': '区域配送中心',
        'Business Hours': '营业时间',
        'Send A Message': '发送消息',
        'Free Consultancy': '免费咨询',
        'Notifications': '通知',
        'Mark All Read': '全部标为已读',
        'Filters': '筛选',
        'All': '全部',
        'Unread': '未读',
        'Orders': '订单',
        'Promotions': '促销',
        'Inventory': '库存',
        'No notifications': '暂无通知',
        'All Categories': '所有分类',
        'Browse all product categories': '浏览所有商品分类',
        'Add to favourite': '添加到收藏',
        'Add to favourites': '添加到收藏',
        'Add to wishlist': '添加到愿望清单',
        'Added to wishlist': '已加入愿望清单',
        'Add to Compare': '添加到对比',
        'My Account': '我的账户',
        'Contact': '联系我们',
        'Color': '颜色',
        'Dark': '深色',
        'Sale': '促销',
        'Summer Electronics': '夏季电子产品',
        'Compare': '对比',
        'Wishlist': '愿望清单',
        'Favourites': '收藏',
        'Cart': '购物车',
        'Shop': '商店',
        'Home': '首页',
        'Categories': '分类',
        'Name*': '姓名*',
        'Email Address*': '电子邮件地址*',
        'Phone Number': '电话号码',
        'Website': '网站',
        'Your message...*': '您的留言...*',
        'Stay updated with order status, promotions, and important updates': '随时了解订单状态、促销活动和重要更新',
        'Items you frequently purchase or access': '您经常购买或访问的商品',
        'Save items for later and track price changes': '保存商品以备后用并跟踪价格变化',
        'Search items on Aveenix…': '在 Aveenix 上搜索商品…',
        'My Account': '我的账户',
        'Notifications': '通知',
        'Color Theme': '颜色主题',
        'Popular': '热门',
        'Extended Palette': '扩展调色板',
        'Contact support team': '联系支持团队',
        'Monday – Sunday: 06:00 – 18:00': '周一至周日：06:00 – 18:00',
        'Public Holidays – Closed': '公众假期 – 休息',
        'Login': '登录',
        'Default': '默认',
        'Yellow': '黄色',
        'Blue': '蓝色',
        'Green': '绿色',
        'Purple': '紫色',
        'Red': '红色',
        'Orange': '橙色',
        'Teal': '青蓝色',
        'Indigo': '靛蓝',
        'Pink': '粉色',
        'Lime': '黄绿色',
        'Cyan': '青色',
        'Amber': '琥珀色',
        'Emerald': '翡翠绿',
        'Violet': '紫罗兰',
        'Rose': '玫瑰色',
        'Sky': '天蓝色',
        'Fuchsia': '品红',
        'Slate': '石板灰',
        'Log Out': '退出登录',
        'products': '产品',
        'Recent Searches': '最近搜索',
        'Trending Searches': '热门搜索',
        'Customer Service': '客户服务',
        'Information': '信息',
        'Account': '账户',
        'Support': '支持',
        'Legal': '法律',
        'Settings': '设置',
        'Website': '网站',
        'Discover the latest trends in fashion': '探索最新时尚潮流',
        'Get the latest gadgets at unbeatable prices': '以无与伦比的价格获取最新电子产品',
        'Fashion Week Special': '时装周特惠',
        'Beautiful furniture and decor for every room': '每个房间都有精美的家具和装饰',
        'Transform Your Space': '改变您的空间',
        'Aveenix Express': 'Aveenix 快递',
        'Regional Delivery Centers': '区域配送中心',
        'Products to Compare': '待对比商品',
        'Compare features, pricing, and specifications side-by-side': '并排比较功能、价格和规格',
        'Start Comparing Products': '开始对比商品',
        'Add to favourite': '添加到收藏',
        'Add to favourites': '添加到收藏',
        'Add to wishlist': '添加到愿望清单',
        'Added to wishlist': '已加入愿望清单',
        'Add to Compare': '添加到对比',
        'No favourites yet': '暂无收藏',
        'Add products to your favourites by clicking the heart icon on product cards': '点击商品卡片上的心形图标将商品添加到收藏',
        'Add products to your wishlist by clicking the star icon on product cards': '点击商品卡片上的星形图标将商品添加到愿望清单',
        'Total Wishlist': '愿望清单总数',
        'Your wishlist is empty': '您的愿望清单为空',
        'All Items': '全部商品',
        'Toggle View': '切换视图',
        'Total Favourites': '收藏总数',
        'Stay updated with order status, promotions, and important updates': '随时了解订单状态、促销活动和重要更新',
        'Items you frequently purchase or access': '您经常购买或访问的商品',
        'Save items for later and track price changes': '保存商品以备后用并跟踪价格变化',
        'Search items on Aveenix…': '在 Aveenix 上搜索商品…',
        'Color Theme': '颜色主题',
        'Popular': '热门',
        'Extended Palette': '扩展调色板',
        'Contact support team': '联系支持团队',
        'Browse all product categories': '浏览所有商品分类',
        'View All Categories →': '查看所有分类 →',
        'Get ': '获取',
        '$20 OFF': '优惠20美元',
        ' your first order!': '您的第一笔订单！',
        'Enter your email': '输入您的电子邮件',
        'Get $20 OFF': '立减20美元',
        'Country': '国家',
        'Language': '语言',
        'Currency': '货币',
        'Dark Mode': '深色模式',
        'POPULAR': '热门',
        'EXTENDED PALETTE': '扩展调色板',
        'Download on App Store': '在 App Store 下载',
        'Get it on Google Play': '在 Google Play 获取',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. 保留所有权利。',
        'Privacy Policy': '隐私政策',
        'Cookie Policy': 'Cookie 政策',
        'Contact Support': '联系支持',
        'Search products, brands, categories…': '搜索产品、品牌、分类…',
        'Contact us': '联系我们',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "有疑问或需要帮助？我们随时为您服务！在 Aveenix，您的满意是我们的首要任务。无论您对订单有疑问、需要网站使用帮助，还是只想联系我们，我们专属的支持团队都会随时为您提供帮助。",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "请通过下方联系表单联系我们，我们将迅速为您回复。享受 Aveenix 带来的流畅购物体验，我们致力于让您的网上购物之旅与众不同。放心购物，我们随时待命！",
        'Site Us': '关于我们',
        'FAQs': '常见问题',
        'Order Tracking': '订单追踪',
        'Features': '功能',
        'Partners': '合作伙伴',
        'Shipping Policy': '配送政策',
        'Services': '服务',
        'Connect Aveenix': '连接 Aveenix',
        'Registration': '注册',
        'Purple Parlay': 'Purple Parlay',
        'Tarcount': 'Tarcount',
        'Career Policy': '职业政策',
        'Terms of Use': '使用条款',
        'TV & Video': '电视与视频',
        'Cameras': '相机',
        'Toggle dark mode': '切换深色模式',
        'Search': '搜索',
        '✕ Clear All': '✕ 清除全部',
        '0 of 0 notifications': '0 条通知中的 0 条',
        "You're all caught up!": '您已全部读完！',
        'New Arrivals': '新品上市',
        'Laptop': '笔记本',
        'Smartphone': '智能手机',
        'Smart TV': '智能电视',
        'Tablet': '平板',
        'Camera': '相机',
        'Watch': '手表',
    },
    'fr': {
        'Up to 70% Off': "Jusqu'à 70% de réduction",
        'Get the latest gadgets at unbeatable prices': "Obtenez les derniers gadgets à des prix imbattables",
        'Shop Now': 'Acheter maintenant',
        'Fashion Week Special': 'Spécial Semaine de la Mode',
        'New Arrivals': 'Nouveautés',
        'Discover the latest trends in fashion': "Découvrez les dernières tendances de la mode",
        'Explore': 'Explorer',
        'Transform Your Space': 'Transformez votre espace',
        'Beautiful furniture and decor for every room': "De beaux meubles et décorations pour chaque pièce",
        'Browse': 'Parcourir',
        'Previous': 'Précédent',
        'Next': 'Suivant',
        'Shop by Category': 'Acheter par catégorie',
        'For You': 'Pour vous',
        'Best Sellers': 'Meilleures ventes',
        'View All': 'Voir tout',
        'Laptops': 'Ordinateurs portables',
        'Mobile': 'Mobile',
        'Gaming': 'Jeux vidéo',
        'Monitors': 'Moniteurs',
        'Headphones': 'Casques audio',
        'Smart Home': 'Maison connectée',
        'Trending Products': 'Produits tendance',
        'Add to Cart': 'Ajouter au panier',
        'Why Choose Aveenix?': 'Pourquoi choisir Aveenix ?',
        'Secure Payments': 'Paiements sécurisés',
        'Safe and secure payment methods guaranteed.': 'Méthodes de paiement sûres et sécurisées garanties.',
        'Fast Delivery': 'Livraison rapide',
        'Current shipping at supreme delivery speeds.': "Expédition actuelle à des vitesses de livraison suprêmes.",
        'Hassle Free Returns': 'Retours sans tracas',
        'Simple and easy return policy for all products.': 'Politique de retour simple et facile pour tous les produits.',
        '24/7 Support': 'Support 24h/24 7j/7',
        'Round-the-clock customer support team.': "Équipe de support client disponible en permanence.",
        'Sell on Aveenix': 'Vendre sur Aveenix',
        'Reach millions of customers by becoming a seller on AVEENIX': "Atteignez des millions de clients en devenant vendeur sur AVEENIX",
        'Start Selling': 'Commencer à vendre',
        'Compare Products': 'Comparer les produits',
        'Back to Home': "Retour à l'accueil",
        'Products to Compare': 'Produits à comparer',
        'Total Value': 'Valeur totale',
        'In Stock': 'En stock',
        'On Sale': 'En promotion',
        'Add All to Cart': 'Tout ajouter au panier',
        'Clear Comparison': 'Effacer la comparaison',
        '0 items': '0 article',
        'Start Comparing Products': 'Commencer à comparer des produits',
        'Add Products': 'Ajouter des produits',
        'My Favourites': 'Mes favoris',
        'All Items': 'Tous les articles',
        'Toggle View': 'Changer de vue',
        'List View': 'Vue liste',
        'Total Favourites': 'Total des favoris',
        'Clear Favourites': 'Effacer les favoris',
        'No favourites yet': 'Pas encore de favoris',
        'Add products to your favourites by clicking the heart icon on product cards': "Ajoutez des produits à vos favoris en cliquant sur l'icône cœur",
        'Start Shopping': 'Commencer les achats',
        'My Wishlist': 'Ma liste de souhaits',
        'Total Wishlist': 'Total de la liste de souhaits',
        'Clear Wishlist': 'Vider la liste de souhaits',
        'Your wishlist is empty': 'Votre liste de souhaits est vide',
        'Add products to your wishlist by clicking the star icon on product cards': "Ajoutez des produits à votre liste en cliquant sur l'icône étoile",
        'Contact Us': 'Contactez-nous',
        'Location': 'Adresse',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Centres de livraison régionaux',
        'Business Hours': "Heures d'ouverture",
        'Send A Message': 'Envoyer un message',
        'Free Consultancy': 'Consultation gratuite',
        'Notifications': 'Notifications',
        'Mark All Read': 'Tout marquer comme lu',
        'Filters': 'Filtres',
        'All': 'Tous',
        'Unread': 'Non lu',
        'Orders': 'Commandes',
        'Promotions': 'Promotions',
        'Inventory': 'Inventaire',
        'No notifications': 'Aucune notification',
        'All Categories': 'Toutes les catégories',
        'View All Categories': 'Voir toutes les catégories',
        'Browse all product categories': 'Parcourir toutes les catégories de produits',
        'Add to favourite': 'Ajouter aux favoris',
        'Add to favourites': 'Ajouter aux favoris',
        'Add to wishlist': 'Ajouter à la liste de souhaits',
        'Added to wishlist': 'Ajouté à la liste de souhaits',
        'Add to Compare': 'Ajouter à la comparaison',
        'My Account': 'Mon compte',
        'Contact': 'Contact',
        'Color': 'Couleur',
        'Dark': 'Sombre',
        'Sale': 'Soldes',
        'Summer Electronics': "Vente d'électronique d'été",
        'Compare': 'Comparer',
        'Wishlist': 'Liste de souhaits',
        'Favourites': 'Favoris',
        'Cart': 'Panier',
        'Shop': 'Boutique',
        'Home': 'Accueil',
        'Categories': 'Catégories',
        'Name*': 'Nom*',
        'Email Address*': 'Adresse e-mail*',
        'Phone Number': 'Numéro de téléphone',
        'Your message...*': 'Votre message...*',
        'Stay updated with order status, promotions, and important updates': 'Restez informé du statut des commandes, des promotions et des mises à jour importantes',
        'Compare features, pricing, and specifications side-by-side': 'Comparer les fonctionnalités, les prix et les spécifications côte à côte',
        'Items you frequently purchase or access': 'Articles que vous consultez fréquemment',
        'Save items for later and track price changes': 'Sauvegarder des articles pour plus tard',
        'Search items on Aveenix…': 'Rechercher des articles sur Aveenix…',
        'Color Theme': 'Thème de couleur',
        'Popular': 'Populaire',
        'Extended Palette': 'Palette étendue',
        'Contact support team': "Contacter l'équipe de support",
        'Monday – Sunday: 06:00 – 18:00': 'Lundi – Dimanche : 06:00 – 18:00',
        'Public Holidays – Closed': 'Jours fériés – Fermé',
        'Login': 'Connexion',
        'Default': 'Défaut',
        'Yellow': 'Jaune', 'Blue': 'Bleu', 'Green': 'Vert', 'Purple': 'Violet',
        'Red': 'Rouge', 'Orange': 'Orange', 'Teal': 'Sarcelle', 'Indigo': 'Indigo',
        'Pink': 'Rose', 'Lime': 'Citron vert', 'Cyan': 'Cyan', 'Amber': 'Ambre',
        'Emerald': 'Émeraude', 'Violet': 'Violet', 'Rose': 'Rose foncé',
        'Sky': 'Ciel', 'Fuchsia': 'Fuchsia', 'Slate': 'Ardoise',
        'Log Out': 'Se déconnecter',
        'products': 'produits',
        'Recent Searches': 'Recherches récentes',
        'Trending Searches': 'Recherches tendance',
        'Customer Service': 'Service client',
        'Information': 'Informations',
        'Account': 'Compte',
        'Support': 'Support',
        'Legal': 'Mentions légales',
        'Settings': 'Paramètres',
        'Website': 'Site web',
        'Get the latest gadgets at unbeatable prices': 'Obtenez les derniers gadgets à des prix imbattables',
        'Fashion Week Special': 'Spécial Semaine de la Mode',
        'Discover the latest trends in fashion': 'Découvrez les dernières tendances de la mode',
        'Beautiful furniture and decor for every room': 'De beaux meubles et décorations pour chaque pièce',
        'Transform Your Space': 'Transformez votre espace',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Centres de livraison régionaux',
        'Products to Compare': 'Produits à comparer',
        'Compare features, pricing, and specifications side-by-side': 'Comparer les fonctionnalités, les prix et les spécifications côte à côte',
        'Start Comparing Products': 'Commencer à comparer des produits',
        'Add to favourite': 'Ajouter aux favoris',
        'Add to favourites': 'Ajouter aux favoris',
        'Add to wishlist': 'Ajouter à la liste de souhaits',
        'Added to wishlist': 'Ajouté à la liste de souhaits',
        'Add to Compare': 'Ajouter à la comparaison',
        'No favourites yet': 'Pas encore de favoris',
        'Add products to your favourites by clicking the heart icon on product cards': "Ajoutez des produits à vos favoris en cliquant sur l'icône cœur",
        'Add products to your wishlist by clicking the star icon on product cards': "Ajoutez des produits à votre liste en cliquant sur l'icône étoile",
        'Total Wishlist': 'Total de la liste de souhaits',
        'Your wishlist is empty': 'Votre liste de souhaits est vide',
        'All Items': 'Tous les articles',
        'Toggle View': 'Changer de vue',
        'Total Favourites': 'Total des favoris',
        'Stay updated with order status, promotions, and important updates': 'Restez informé du statut des commandes, des promotions et des mises à jour importantes',
        'Items you frequently purchase or access': 'Articles que vous consultez fréquemment',
        'Save items for later and track price changes': 'Sauvegarder des articles pour plus tard',
        'Search items on Aveenix…': 'Rechercher des articles sur Aveenix…',
        'Color Theme': 'Thème de couleur',
        'Popular': 'Populaire',
        'Extended Palette': 'Palette étendue',
        'Contact support team': "Contacter l'équipe de support",
        'Browse all product categories': 'Parcourir toutes les catégories de produits',
        'View All Categories →': 'Voir toutes les catégories →',
        'Get ': 'Obtenez ',
        '$20 OFF': '20 $ de réduction',
        ' your first order!': ' sur votre première commande !',
        'Enter your email': 'Entrez votre e-mail',
        'Get $20 OFF': 'Obtenir 20 $ de réduction',
        'Country': 'Pays',
        'Language': 'Langue',
        'Currency': 'Devise',
        'Dark Mode': 'Mode sombre',
        'POPULAR': 'POPULAIRE',
        'EXTENDED PALETTE': 'PALETTE ÉTENDUE',
        'Download on App Store': "Télécharger sur l'App Store",
        'Get it on Google Play': 'Disponible sur Google Play',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. Tous droits réservés.',
        'Privacy Policy': 'Politique de confidentialité',
        'Cookie Policy': 'Politique relative aux cookies',
        'Contact Support': 'Contacter le support',
        'Search products, brands, categories…': 'Rechercher des produits, marques, catégories…',
        'Contact us': 'Contactez-nous',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "Vous avez des questions ou besoin d'aide ? Nous sommes là pour vous ! Chez Aveenix, votre satisfaction est notre priorité absolue. Que vous ayez des questions sur votre commande, que vous ayez besoin d'aide pour naviguer sur notre site ou que vous souhaitiez simplement nous contacter, notre équipe d'assistance dédiée est prête à vous aider.",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "Contactez-nous via le formulaire de contact ci-dessous pour une réponse rapide et utile. Profitez d'une expérience d'achat fluide avec Aveenix, où nous nous engageons à rendre votre parcours en ligne exceptionnel. Achetez en toute confiance en sachant que nous ne sommes qu'à un message !",
        'TV & Video': 'TV et vidéo',
        'Cameras': 'Caméras',
        'Headphones': 'Casques audio',
        'Mobile': 'Mobiles',
        'Smart Home': 'Maison connectée',
        'Gaming': 'Jeux vidéo',
        'Laptops': 'Ordinateurs portables',
        'Site Us': 'À propos de nous',
        'FAQs': 'FAQ',
        'Order Tracking': 'Suivi de commande',
        'Features': 'Fonctionnalités',
        'Partners': 'Partenaires',
        'Shipping Policy': "Politique d'expédition",
        'Services': 'Services',
        'Connect Aveenix': 'Se connecter à Aveenix',
        'Registration': 'Inscription',
        'Purple Parlay': 'Purple Parlay',
        'Tarcount': 'Tarcount',
        'Career Policy': 'Politique de carrière',
        'Terms of Use': "Conditions d'utilisation",
        'Toggle dark mode': 'Basculer le mode sombre',
        'Search': 'Rechercher',
        '✕ Clear All': '✕ Tout effacer',
        '0 of 0 notifications': '0 notification sur 0',
        "You're all caught up!": 'Vous avez tout lu !',
        'New Arrivals': 'Nouveautés',
        'Laptop': 'Ordinateur portable',
        'Smartphone': 'Smartphone',
        'Smart TV': 'Télévision connectée',
        'Tablet': 'Tablette',
        'Camera': 'Appareil photo',
        'Watch': 'Montre',
    },
    'de': {
        'Up to 70% Off': 'Bis zu 70% Rabatt',
        'Get the latest gadgets at unbeatable prices': 'Holen Sie sich die neuesten Gadgets zu unschlagbaren Preisen',
        'Shop Now': 'Jetzt kaufen',
        'Fashion Week Special': 'Fashion Week Special',
        'New Arrivals': 'Neuheiten',
        'Discover the latest trends in fashion': 'Entdecken Sie die neuesten Modetrends',
        'Explore': 'Entdecken',
        'Transform Your Space': 'Verwandeln Sie Ihren Raum',
        'Beautiful furniture and decor for every room': 'Wunderschöne Möbel und Dekor für jedes Zimmer',
        'Browse': 'Durchstöbern',
        'Previous': 'Zurück',
        'Next': 'Weiter',
        'Shop by Category': 'Nach Kategorie einkaufen',
        'For You': 'Für Sie',
        'Best Sellers': 'Bestseller',
        'View All': 'Alle anzeigen',
        'Laptops': 'Laptops',
        'Mobile': 'Mobiltelefone',
        'Gaming': 'Gaming',
        'Monitors': 'Monitore',
        'Headphones': 'Kopfhörer',
        'Smart Home': 'Smart Home',
        'Trending Products': 'Trendprodukte',
        'Add to Cart': 'In den Warenkorb',
        'Why Choose Aveenix?': 'Warum Aveenix wählen?',
        'Secure Payments': 'Sichere Zahlungen',
        'Safe and secure payment methods guaranteed.': 'Sichere und zuverlässige Zahlungsmethoden garantiert.',
        'Fast Delivery': 'Schnelle Lieferung',
        'Current shipping at supreme delivery speeds.': 'Aktuelle Lieferung mit höchster Geschwindigkeit.',
        'Hassle Free Returns': 'Problemlose Rücksendungen',
        'Simple and easy return policy for all products.': 'Einfache und unkomplizierte Rückgaberichtlinie für alle Produkte.',
        '24/7 Support': '24/7 Support',
        'Round-the-clock customer support team.': 'Rund-um-die-Uhr-Kundensupport-Team.',
        'Sell on Aveenix': 'Auf Aveenix verkaufen',
        'Reach millions of customers by becoming a seller on AVEENIX': 'Erreichen Sie Millionen von Kunden, indem Sie Verkäufer bei AVEENIX werden',
        'Start Selling': 'Mit dem Verkaufen beginnen',
        'Compare Products': 'Produkte vergleichen',
        'Back to Home': 'Zurück zur Startseite',
        'Products to Compare': 'Zu vergleichende Produkte',
        'Total Value': 'Gesamtwert',
        'In Stock': 'Auf Lager',
        'On Sale': 'Im Angebot',
        'Add All to Cart': 'Alle in den Warenkorb',
        'Clear Comparison': 'Vergleich löschen',
        '0 items': '0 Artikel',
        'Start Comparing Products': 'Produkte vergleichen beginnen',
        'Add Products': 'Produkte hinzufügen',
        'My Favourites': 'Meine Favoriten',
        'All Items': 'Alle Artikel',
        'Toggle View': 'Ansicht wechseln',
        'List View': 'Listenansicht',
        'Total Favourites': 'Favoriten gesamt',
        'Clear Favourites': 'Favoriten löschen',
        'No favourites yet': 'Noch keine Favoriten',
        'Add products to your favourites by clicking the heart icon on product cards': 'Klicken Sie auf das Herzsymbol auf den Produktkarten',
        'Start Shopping': 'Einkaufen beginnen',
        'My Wishlist': 'Meine Wunschliste',
        'Total Wishlist': 'Wunschliste gesamt',
        'Clear Wishlist': 'Wunschliste löschen',
        'Your wishlist is empty': 'Ihre Wunschliste ist leer',
        'Add products to your wishlist by clicking the star icon on product cards': 'Klicken Sie auf das Sternsymbol auf den Produktkarten',
        'Contact Us': 'Kontaktieren Sie uns',
        'Location': 'Standort',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Regionale Lieferzentren',
        'Business Hours': 'Geschäftszeiten',
        'Send A Message': 'Nachricht senden',
        'Free Consultancy': 'Kostenlose Beratung',
        'Notifications': 'Benachrichtigungen',
        'Mark All Read': 'Alle als gelesen markieren',
        'Filters': 'Filter',
        'All': 'Alle',
        'Unread': 'Ungelesen',
        'Orders': 'Bestellungen',
        'Promotions': 'Aktionen',
        'Inventory': 'Inventar',
        'No notifications': 'Keine Benachrichtigungen',
        'All Categories': 'Alle Kategorien',
        'Browse all product categories': 'Alle Produktkategorien durchsuchen',
        'Add to favourite': 'Zu Favoriten hinzufügen',
        'Add to favourites': 'Zu Favoriten hinzufügen',
        'Add to wishlist': 'Zur Wunschliste hinzufügen',
        'Added to wishlist': 'Zur Wunschliste hinzugefügt',
        'Add to Compare': 'Zum Vergleich hinzufügen',
        'My Account': 'Mein Konto',
        'Contact': 'Kontakt',
        'Color': 'Farbe',
        'Dark': 'Dunkel',
        'Sale': 'Angebot',
        'Summer Electronics': 'Sommer-Elektronik',
        'Compare': 'Vergleichen',
        'Wishlist': 'Wunschliste',
        'Favourites': 'Favoriten',
        'Cart': 'Warenkorb',
        'Shop': 'Shop',
        'Home': 'Startseite',
        'Categories': 'Kategorien',
        'Name*': 'Name*',
        'Email Address*': 'E-Mail-Adresse*',
        'Phone Number': 'Telefonnummer',
        'Your message...*': 'Ihre Nachricht...*',
        'Stay updated with order status, promotions, and important updates': 'Bleiben Sie über Bestellstatus, Aktionen und wichtige Updates informiert',
        'Compare features, pricing, and specifications side-by-side': 'Funktionen, Preise und Spezifikationen nebeneinander vergleichen',
        'Items you frequently purchase or access': 'Häufig gekaufte Artikel',
        'Save items for later and track price changes': 'Artikel für später speichern',
        'Search items on Aveenix…': 'Artikel auf Aveenix suchen…',
        'Color Theme': 'Farbthema',
        'Popular': 'Beliebt',
        'Extended Palette': 'Erweiterte Palette',
        'Contact support team': 'Support-Team kontaktieren',
        'Monday – Sunday: 06:00 – 18:00': 'Montag – Sonntag: 06:00 – 18:00',
        'Public Holidays – Closed': 'Feiertage – Geschlossen',
        'Login': 'Anmelden',
        'Default': 'Standard',
        'Yellow': 'Gelb', 'Blue': 'Blau', 'Green': 'Grün', 'Purple': 'Lila',
        'Red': 'Rot', 'Orange': 'Orange', 'Teal': 'Türkis', 'Indigo': 'Indigo',
        'Pink': 'Rosa', 'Lime': 'Limette', 'Cyan': 'Cyan', 'Amber': 'Bernstein',
        'Emerald': 'Smaragd', 'Violet': 'Violett', 'Rose': 'Rosarot',
        'Sky': 'Himmelblau', 'Fuchsia': 'Fuchsia', 'Slate': 'Schiefer',
        'Log Out': 'Abmelden',
        'products': 'Produkte',
        'Recent Searches': 'Letzte Suchanfragen',
        'Trending Searches': 'Trendsuchen',
        'Customer Service': 'Kundenservice',
        'Information': 'Informationen',
        'Account': 'Konto',
        'Support': 'Support',
        'Legal': 'Rechtliches',
        'Settings': 'Einstellungen',
        'Website': 'Webseite',
        'Get the latest gadgets at unbeatable prices': 'Holen Sie sich die neuesten Gadgets zu unschlagbaren Preisen',
        'Fashion Week Special': 'Fashion Week Special',
        'Discover the latest trends in fashion': 'Entdecken Sie die neuesten Modetrends',
        'Beautiful furniture and decor for every room': 'Wunderschöne Möbel und Dekor für jedes Zimmer',
        'Transform Your Space': 'Verwandeln Sie Ihren Raum',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Regionale Lieferzentren',
        'Products to Compare': 'Zu vergleichende Produkte',
        'Compare features, pricing, and specifications side-by-side': 'Funktionen, Preise und Spezifikationen nebeneinander vergleichen',
        'Start Comparing Products': 'Produkte vergleichen beginnen',
        'Add to favourite': 'Zu Favoriten hinzufügen',
        'Add to favourites': 'Zu Favoriten hinzufügen',
        'Add to wishlist': 'Zur Wunschliste hinzufügen',
        'Added to wishlist': 'Zur Wunschliste hinzugefügt',
        'Add to Compare': 'Zum Vergleich hinzufügen',
        'No favourites yet': 'Noch keine Favoriten',
        'Add products to your favourites by clicking the heart icon on product cards': 'Klicken Sie auf das Herzsymbol auf den Produktkarten',
        'Add products to your wishlist by clicking the star icon on product cards': 'Klicken Sie auf das Sternsymbol auf den Produktkarten',
        'Total Wishlist': 'Wunschliste gesamt',
        'Your wishlist is empty': 'Ihre Wunschliste ist leer',
        'All Items': 'Alle Artikel',
        'Toggle View': 'Ansicht wechseln',
        'Total Favourites': 'Favoriten gesamt',
        'Stay updated with order status, promotions, and important updates': 'Bleiben Sie über Bestellstatus, Aktionen und wichtige Updates informiert',
        'Items you frequently purchase or access': 'Häufig gekaufte Artikel',
        'Save items for later and track price changes': 'Artikel für später speichern',
        'Search items on Aveenix…': 'Artikel auf Aveenix suchen…',
        'Color Theme': 'Farbthema',
        'Popular': 'Beliebt',
        'Extended Palette': 'Erweiterte Palette',
        'Contact support team': 'Support-Team kontaktieren',
        'Browse all product categories': 'Alle Produktkategorien durchsuchen',
        'View All Categories →': 'Alle Kategorien anzeigen →',
        'Get ': 'Erhalten Sie ',
        '$20 OFF': '20 $ Rabatt',
        ' your first order!': ' auf Ihre erste Bestellung!',
        'Enter your email': 'E-Mail eingeben',
        'Get $20 OFF': '20 $ Rabatt erhalten',
        'Country': 'Land',
        'Language': 'Sprache',
        'Currency': 'Währung',
        'Dark Mode': 'Dunkelmodus',
        'POPULAR': 'BELIEBT',
        'EXTENDED PALETTE': 'ERWEITERTE PALETTE',
        'Download on App Store': 'Im App Store laden',
        'Get it on Google Play': 'Bei Google Play erhältlich',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. Alle Rechte vorbehalten.',
        'Privacy Policy': 'Datenschutzrichtlinie',
        'Cookie Policy': 'Cookie-Richtlinie',
        'Contact Support': 'Support kontaktieren',
        'Search products, brands, categories…': 'Produkte, Marken, Kategorien suchen…',
        'Contact us': 'Kontaktieren Sie uns',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "Haben Sie Fragen oder benötigen Sie Hilfe? Wir sind für Sie da! Bei Aveenix steht Ihre Zufriedenheit an erster Stelle. Ob Sie Fragen zu Ihrer Bestellung haben, Hilfe beim Navigieren unserer Website benötigen oder einfach Kontakt aufnehmen möchten – unser engagiertes Support-Team steht Ihnen zur Verfügung.",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "Nutzen Sie das Kontaktformular unten für eine schnelle und hilfreiche Antwort. Genießen Sie ein reibungsloses Einkaufserlebnis mit Aveenix, wo wir uns verpflichten, Ihre Online-Reise außergewöhnlich zu machen. Kaufen Sie mit Vertrauen – wir sind nur eine Nachricht entfernt!",
        'Site Us': 'Über uns',
        'FAQs': 'FAQs',
        'Order Tracking': 'Bestellverfolgung',
        'Features': 'Funktionen',
        'Partners': 'Partner',
        'Shipping Policy': 'Versandrichtlinie',
        'Services': 'Dienstleistungen',
        'Connect Aveenix': 'Mit Aveenix verbinden',
        'Registration': 'Registrierung',
        'Career Policy': 'Karriererichtlinie',
        'Terms of Use': 'Nutzungsbedingungen',
        'TV & Video': 'TV & Video',
        'Cameras': 'Kameras',
        'Toggle dark mode': 'Dunkelmodus umschalten',
        'Search': 'Suchen',
        '✕ Clear All': '✕ Alle löschen',
        '0 of 0 notifications': '0 von 0 Benachrichtigungen',
        "You're all caught up!": 'Sie sind auf dem neuesten Stand!',
        'New Arrivals': 'Neuheiten',
        'Laptop': 'Laptop',
        'Smartphone': 'Smartphone',
        'Smart TV': 'Smart TV',
        'Tablet': 'Tablet',
        'Camera': 'Kamera',
        'Watch': 'Uhr',
    },
    'es': {
        'Up to 70% Off': 'Hasta 70% de descuento',
        'Shop Now': 'Comprar ahora', 'New Arrivals': 'Nuevas llegadas', 'Explore': 'Explorar',
        'Browse': 'Explorar', 'Previous': 'Anterior', 'Next': 'Siguiente',
        'Shop by Category': 'Comprar por categoría', 'For You': 'Para ti',
        'Best Sellers': 'Más vendidos', 'View All': 'Ver todo', 'Laptops': 'Portátiles',
        'Mobile': 'Móvil', 'Gaming': 'Gaming', 'Monitors': 'Monitores',
        'Headphones': 'Auriculares', 'Smart Home': 'Hogar inteligente',
        'Trending Products': 'Productos en tendencia', 'Add to Cart': 'Añadir al carrito',
        'Why Choose Aveenix?': '¿Por qué elegir Aveenix?', 'Secure Payments': 'Pagos seguros',
        'Safe and secure payment methods guaranteed.': 'Métodos de pago seguros y confiables garantizados.',
        'Fast Delivery': 'Entrega rápida',
        'Current shipping at supreme delivery speeds.': 'Envío actual a velocidades de entrega supremas.',
        'Hassle Free Returns': 'Devoluciones sin complicaciones',
        'Simple and easy return policy for all products.': 'Política de devolución simple y fácil para todos los productos.',
        '24/7 Support': 'Soporte 24/7',
        'Round-the-clock customer support team.': 'Equipo de soporte al cliente disponible las 24 horas.',
        'Sell on Aveenix': 'Vender en Aveenix',
        'Reach millions of customers by becoming a seller on AVEENIX': 'Llega a millones de clientes convirtiéndote en vendedor en AVEENIX',
        'Start Selling': 'Empezar a vender', 'Compare Products': 'Comparar productos',
        'Back to Home': 'Volver al inicio', 'Total Value': 'Valor total',
        'In Stock': 'En stock', 'On Sale': 'En oferta',
        'Add All to Cart': 'Agregar todo al carrito', 'Clear Comparison': 'Limpiar comparación',
        '0 items': '0 artículos', 'Start Comparing Products': 'Empezar a comparar productos',
        'Add Products': 'Agregar productos', 'My Favourites': 'Mis favoritos',
        'All Items': 'Todos los artículos', 'Toggle View': 'Cambiar vista',
        'List View': 'Vista de lista', 'Total Favourites': 'Total de favoritos',
        'Clear Favourites': 'Limpiar favoritos', 'No favourites yet': 'Aún no hay favoritos',
        'Add products to your favourites by clicking the heart icon on product cards': 'Haga clic en el icono de corazón en las tarjetas de producto',
        'Start Shopping': 'Empezar a comprar', 'My Wishlist': 'Mi lista de deseos',
        'Total Wishlist': 'Total de lista de deseos', 'Clear Wishlist': 'Limpiar lista de deseos',
        'Your wishlist is empty': 'Tu lista de deseos está vacía',
        'Add products to your wishlist by clicking the star icon on product cards': 'Haga clic en el icono de estrella en las tarjetas de producto',
        'Contact Us': 'Contáctanos', 'Location': 'Ubicación',
        'Aveenix Express': 'Aveenix Express', 'Regional Delivery Centers': 'Centros de entrega regionales',
        'Business Hours': 'Horario de atención', 'Send A Message': 'Enviar un mensaje',
        'Free Consultancy': 'Consultoría gratuita', 'Notifications': 'Notificaciones',
        'Mark All Read': 'Marcar todo como leído', 'Filters': 'Filtros',
        'All': 'Todos', 'Unread': 'No leído', 'Orders': 'Pedidos',
        'Promotions': 'Promociones', 'Inventory': 'Inventario', 'No notifications': 'Sin notificaciones',
        'All Categories': 'Todas las categorías',
        'Browse all product categories': 'Explorar todas las categorías de productos',
        'Add to favourite': 'Agregar a favoritos', 'Add to favourites': 'Agregar a favoritos',
        'Add to wishlist': 'Agregar a lista de deseos', 'Added to wishlist': 'Agregado a lista de deseos',
        'Add to Compare': 'Agregar a comparación', 'My Account': 'Mi cuenta',
        'Contact': 'Contacto', 'Color': 'Color', 'Dark': 'Oscuro', 'Sale': 'Oferta',
        'Summer Electronics': 'Electrónica de verano',
        'Compare': 'Comparar', 'Wishlist': 'Lista de deseos', 'Favourites': 'Favoritos',
        'Cart': 'Carrito', 'Shop': 'Tienda', 'Home': 'Inicio', 'Categories': 'Categorías',
        'Name*': 'Nombre*', 'Email Address*': 'Dirección de correo electrónico*',
        'Phone Number': 'Número de teléfono', 'Your message...*': 'Tu mensaje...*',
        'Stay updated with order status, promotions, and important updates': 'Mantente actualizado con el estado de los pedidos, promociones y actualizaciones importantes',
        'Compare features, pricing, and specifications side-by-side': 'Comparar características, precios y especificaciones lado a lado',
        'Items you frequently purchase or access': 'Artículos que compras con frecuencia',
        'Save items for later and track price changes': 'Guardar artículos para después',
        'Search items on Aveenix…': 'Buscar artículos en Aveenix…',
        'Color Theme': 'Tema de color', 'Popular': 'Popular', 'Extended Palette': 'Paleta extendida',
        'Contact support team': 'Contactar al equipo de soporte',
        'Monday – Sunday: 06:00 – 18:00': 'Lunes – Domingo: 06:00 – 18:00',
        'Public Holidays – Closed': 'Días festivos – Cerrado',
        'Login': 'Iniciar sesión',
        'Default': 'Predeterminado',
        'Yellow': 'Amarillo', 'Blue': 'Azul', 'Green': 'Verde', 'Purple': 'Morado',
        'Red': 'Rojo', 'Orange': 'Naranja', 'Teal': 'Cerceta', 'Indigo': 'Índigo',
        'Pink': 'Rosa', 'Lime': 'Lima', 'Cyan': 'Cian', 'Amber': 'Ámbar',
        'Emerald': 'Esmeralda', 'Violet': 'Violeta', 'Rose': 'Rosa oscuro',
        'Sky': 'Cielo', 'Fuchsia': 'Fucsia', 'Slate': 'Pizarra',
        'Log Out': 'Cerrar sesión',
        'products': 'productos',
        'Recent Searches': 'Búsquedas recientes',
        'Trending Searches': 'Búsquedas populares',
        'Customer Service': 'Servicio al cliente',
        'Information': 'Información',
        'Account': 'Cuenta',
        'Support': 'Soporte',
        'Legal': 'Legal',
        'Settings': 'Configuración',
        'Website': 'Sitio web',
        'Get the latest gadgets at unbeatable prices': 'Obtén los últimos gadgets a precios inmejorables',
        'Fashion Week Special': 'Especial Semana de la Moda',
        'Discover the latest trends in fashion': 'Descubre las últimas tendencias en moda',
        'Beautiful furniture and decor for every room': 'Hermosos muebles y decoración para cada habitación',
        'Transform Your Space': 'Transforma tu espacio',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Centros de entrega regionales',
        'Products to Compare': 'Productos a comparar',
        'Compare features, pricing, and specifications side-by-side': 'Comparar características, precios y especificaciones lado a lado',
        'Start Comparing Products': 'Empezar a comparar productos',
        'Safe and secure payment methods guaranteed.': 'Métodos de pago seguros y confiables garantizados.',
        'Current shipping at supreme delivery speeds.': 'Envío actual a velocidades de entrega supremas.',
        'Simple and easy return policy for all products.': 'Política de devolución simple y fácil para todos los productos.',
        'Round-the-clock customer support team.': 'Equipo de soporte al cliente disponible las 24 horas.',
        'Reach millions of customers by becoming a seller on AVEENIX': 'Llega a millones de clientes convirtiéndote en vendedor en AVEENIX',
        'View All Categories →': 'Ver todas las categorías →',
        'Get ': 'Obtén ',
        '$20 OFF': '20 $ de descuento',
        ' your first order!': ' en tu primer pedido!',
        'Enter your email': 'Ingresa tu correo electrónico',
        'Get $20 OFF': 'Obtén 20 $ de descuento',
        'Country': 'País',
        'Language': 'Idioma',
        'Currency': 'Moneda',
        'Dark Mode': 'Modo oscuro',
        'POPULAR': 'POPULAR',
        'EXTENDED PALETTE': 'PALETA EXTENDIDA',
        'Download on App Store': 'Descargar en App Store',
        'Get it on Google Play': 'Disponible en Google Play',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. Todos los derechos reservados.',
        'Privacy Policy': 'Política de privacidad',
        'Cookie Policy': 'Política de cookies',
        'Contact Support': 'Contactar soporte',
        'Search products, brands, categories…': 'Buscar productos, marcas, categorías…',
        'Contact us': 'Contáctenos',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "¿Tiene preguntas o necesita ayuda? ¡Estamos aquí para ayudarle! En Aveenix, su satisfacción es nuestra máxima prioridad. Ya sea que tenga consultas sobre su pedido, necesite ayuda para navegar por nuestro sitio web o simplemente quiera ponerse en contacto, nuestro equipo de soporte dedicado está listo para asistirle.",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "Comuníquese a través del formulario de contacto a continuación para obtener una respuesta rápida y útil. Disfrute de una experiencia de compra fluida con Aveenix, donde nos comprometemos a hacer que su viaje en línea sea excepcional. ¡Compre con confianza sabiendo que estamos a solo un mensaje de distancia!",
        'Site Us': 'Sobre nosotros',
        'FAQs': 'Preguntas frecuentes',
        'Order Tracking': 'Seguimiento de pedido',
        'Features': 'Características',
        'Partners': 'Socios',
        'Shipping Policy': 'Política de envío',
        'Services': 'Servicios',
        'Connect Aveenix': 'Conectar Aveenix',
        'Registration': 'Registro',
        'Career Policy': 'Política de carrera',
        'Terms of Use': 'Términos de uso',
        'TV & Video': 'TV y Video',
        'Cameras': 'Cámaras',
        'Toggle dark mode': 'Cambiar modo oscuro',
        'Search': 'Buscar',
        '✕ Clear All': '✕ Borrar todo',
        '0 of 0 notifications': '0 de 0 notificaciones',
        "You're all caught up!": '¡Estás al día!',
        'Laptop': 'Portátil',
        'Smartphone': 'Smartphone',
        'Smart TV': 'Smart TV',
        'Tablet': 'Tableta',
        'Camera': 'Cámara',
        'Watch': 'Reloj',
    },
    'it': {
        'Up to 70% Off': 'Fino al 70% di sconto',
        'Shop Now': 'Acquista ora', 'New Arrivals': 'Nuovi arrivi', 'Explore': 'Esplora',
        'Browse': 'Sfoglia', 'Previous': 'Precedente', 'Next': 'Successivo',
        'Shop by Category': 'Acquista per categoria', 'For You': 'Per te',
        'Best Sellers': 'Più venduti', 'View All': 'Vedi tutto', 'Laptops': 'Laptop',
        'Monitors': 'Monitor', 'Headphones': 'Cuffie', 'Smart Home': 'Casa intelligente',
        'Trending Products': 'Prodotti di tendenza', 'Add to Cart': 'Aggiungi al carrello',
        'Why Choose Aveenix?': 'Perché scegliere Aveenix?', 'Secure Payments': 'Pagamenti sicuri',
        'Safe and secure payment methods guaranteed.': 'Metodi di pagamento sicuri e affidabili garantiti.',
        'Fast Delivery': 'Consegna rapida',
        'Current shipping at supreme delivery speeds.': 'Spedizione attuale alle massime velocità di consegna.',
        'Hassle Free Returns': 'Resi senza problemi',
        'Simple and easy return policy for all products.': 'Politica di restituzione semplice e facile per tutti i prodotti.',
        '24/7 Support': 'Supporto 24/7',
        'Round-the-clock customer support team.': 'Team di supporto clienti disponibile tutto il giorno.',
        'Sell on Aveenix': 'Vendi su Aveenix',
        'Reach millions of customers by becoming a seller on AVEENIX': 'Raggiungi milioni di clienti diventando un venditore su AVEENIX',
        'Start Selling': 'Inizia a vendere', 'Compare Products': 'Confronta prodotti',
        'Back to Home': 'Torna alla home', 'Total Value': 'Valore totale',
        'In Stock': 'Disponibile', 'On Sale': 'In offerta',
        'Add All to Cart': 'Aggiungi tutto al carrello', 'Clear Comparison': 'Cancella confronto',
        '0 items': '0 articoli', 'Add Products': 'Aggiungi prodotti',
        'My Favourites': 'I miei preferiti', 'All Items': 'Tutti gli articoli',
        'Toggle View': 'Cambia vista', 'List View': 'Vista elenco',
        'Total Favourites': 'Totale preferiti', 'Clear Favourites': 'Cancella preferiti',
        'No favourites yet': 'Nessun preferito ancora', 'Start Shopping': 'Inizia a fare shopping',
        'My Wishlist': 'La mia lista desideri', 'Clear Wishlist': 'Cancella lista desideri',
        'Your wishlist is empty': 'La tua lista desideri è vuota',
        'Contact Us': 'Contattaci', 'Location': 'Indirizzo', 'Business Hours': 'Orario di lavoro',
        'Send A Message': 'Invia un messaggio', 'Free Consultancy': 'Consulenza gratuita',
        'Notifications': 'Notifiche', 'Mark All Read': 'Segna tutto come letto',
        'All': 'Tutti', 'Orders': 'Ordini', 'No notifications': 'Nessuna notifica',
        'All Categories': 'Tutte le categorie', 'Add to favourite': 'Aggiungi ai preferiti',
        'Add to Compare': 'Aggiungi al confronto', 'My Account': 'Il mio account',
        'Contact': 'Contatto', 'Dark': 'Scuro', 'Sale': 'Saldi',
        'Compare': 'Confronta', 'Cart': 'Carrello', 'Shop': 'Negozio', 'Home': 'Home',
        'Log Out': 'Disconnettersi',
        'products': 'prodotti',
        'Recent Searches': 'Ricerche recenti',
        'Trending Searches': 'Ricerche di tendenza',
        'Customer Service': 'Servizio clienti',
        'Information': 'Informazioni',
        'Account': 'Account',
        'Support': 'Supporto',
        'Legal': 'Legale',
        'Settings': 'Impostazioni',
        'Website': 'Sito web',
        'For You': 'Per te',
        'Best Sellers': 'Più venduti',
        'New Arrivals': 'Nuovi arrivi',
        'Mobile': 'Mobile',
        'Gaming': 'Gaming',
        'Get the latest gadgets at unbeatable prices': 'Ottieni i gadget più recenti a prezzi imbattibili',
        'Fashion Week Special': 'Speciale Settimana della Moda',
        'Discover the latest trends in fashion': 'Scopri le ultime tendenze della moda',
        'Beautiful furniture and decor for every room': 'Bellissimi mobili e decorazioni per ogni stanza',
        'Transform Your Space': 'Trasforma il tuo spazio',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Centri di consegna regionali',
        'Products to Compare': 'Prodotti da confrontare',
        'Compare features, pricing, and specifications side-by-side': 'Confronta funzionalità, prezzi e specifiche fianco a fianco',
        'Start Comparing Products': 'Inizia a confrontare prodotti',
        'Add to favourites': 'Aggiungi ai preferiti',
        'Add to wishlist': 'Aggiungi alla lista desideri',
        'Added to wishlist': 'Aggiunto alla lista desideri',
        'Total Wishlist': 'Totale lista desideri',
        'Color': 'Colore',
        'Summer Electronics': 'Elettronica estiva',
        'Wishlist': 'Lista desideri',
        'Favourites': 'Preferiti',
        'Categories': 'Categorie',
        'Name*': 'Nome*',
        'Email Address*': 'Indirizzo email*',
        'Phone Number': 'Numero di telefono',
        'Your message...*': 'Il tuo messaggio...*',
        'Stay updated with order status, promotions, and important updates': 'Resta aggiornato su ordini, promozioni e aggiornamenti importanti',
        'Items you frequently purchase or access': 'Articoli acquistati frequentemente',
        'Save items for later and track price changes': 'Salva articoli per dopo',
        'Search items on Aveenix…': 'Cerca articoli su Aveenix…',
        'Color Theme': 'Tema colore',
        'Popular': 'Popolare',
        'Extended Palette': 'Palette estesa',
        'Contact support team': 'Contatta il team di supporto',
        'Monday – Sunday: 06:00 – 18:00': 'Lunedì – Domenica: 06:00 – 18:00',
        'Public Holidays – Closed': 'Festività – Chiuso',
        'Login': 'Accedi',
        'Default': 'Predefinito',
        'Yellow': 'Giallo', 'Blue': 'Blu', 'Green': 'Verde', 'Purple': 'Viola',
        'Red': 'Rosso', 'Orange': 'Arancione', 'Teal': 'Verde acqua', 'Indigo': 'Indaco',
        'Pink': 'Rosa', 'Lime': 'Lime', 'Cyan': 'Ciano', 'Amber': 'Ambra',
        'Emerald': 'Smeraldo', 'Violet': 'Viola chiaro', 'Rose': 'Rosa scuro',
        'Sky': 'Azzurro', 'Fuchsia': 'Fucsia', 'Slate': 'Ardesia',
        'Browse all product categories': 'Sfoglia tutte le categorie di prodotti',
        'Filters': 'Filtri',
        'Unread': 'Non letto',
        'Promotions': 'Promozioni',
        'Inventory': 'Inventario',
        'View All Categories →': 'Vedi tutte le categorie →',
        'Get ': 'Ottieni ',
        '$20 OFF': '20 $ di sconto',
        ' your first order!': ' sul tuo primo ordine!',
        'Enter your email': 'Inserisci la tua email',
        'Get $20 OFF': 'Ottieni 20 $ di sconto',
        'Country': 'Paese',
        'Language': 'Lingua',
        'Currency': 'Valuta',
        'Dark Mode': 'Modalità scura',
        'POPULAR': 'POPOLARE',
        'EXTENDED PALETTE': 'PALETTE ESTESA',
        'Download on App Store': "Scarica su App Store",
        'Get it on Google Play': 'Disponibile su Google Play',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. Tutti i diritti riservati.',
        'Privacy Policy': 'Informativa sulla privacy',
        'Cookie Policy': 'Informativa sui cookie',
        'Contact Support': 'Contatta il supporto',
        'Search products, brands, categories…': 'Cerca prodotti, marchi, categorie…',
        'Contact us': 'Contattaci',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "Hai domande o hai bisogno di assistenza? Siamo qui per aiutarti! Da Aveenix, la tua soddisfazione è la nostra massima priorità. Che tu abbia domande sul tuo ordine, abbia bisogno di aiuto per navigare nel nostro sito o voglia semplicemente metterti in contatto, il nostro team di supporto dedicato è pronto ad assisterti.",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "Contattaci tramite il modulo di contatto qui sotto per una risposta rapida e utile. Goditi un'esperienza di acquisto fluida con Aveenix, dove ci impegniamo a rendere eccezionale il tuo percorso online. Acquista con fiducia sapendo che siamo a solo un messaggio di distanza!",
        'Site Us': 'Chi siamo',
        'FAQs': 'FAQ',
        'Order Tracking': 'Tracciamento ordine',
        'Features': 'Funzionalità',
        'Partners': 'Partner',
        'Shipping Policy': 'Politica di spedizione',
        'Services': 'Servizi',
        'Connect Aveenix': 'Connetti Aveenix',
        'Registration': 'Registrazione',
        'Career Policy': 'Politica di carriera',
        'Terms of Use': 'Termini di utilizzo',
        'TV & Video': 'TV e Video',
        'Cameras': 'Fotocamere',
        'Toggle dark mode': 'Attiva modalità scura',
        'Search': 'Cerca',
        '✕ Clear All': '✕ Cancella tutto',
        '0 of 0 notifications': '0 di 0 notifiche',
        "You're all caught up!": 'Sei in pari!',
        'New Arrivals': 'Nuovi arrivi',
        'Laptop': 'Laptop',
        'Smartphone': 'Smartphone',
        'Smart TV': 'Smart TV',
        'Tablet': 'Tablet',
        'Camera': 'Fotocamera',
        'Watch': 'Orologio',
    },
    'ja': {
        'Up to 70% Off': '最大70%オフ',
        'Shop Now': '今すぐ購入', 'New Arrivals': '新着商品', 'Explore': '探索',
        'Browse': 'ブラウズ', 'Previous': '前へ', 'Next': '次へ',
        'For You': 'あなたへ', 'Best Sellers': 'ベストセラー', 'View All': 'すべて見る',
        'Laptops': 'ラップトップ', 'Mobile': 'モバイル', 'Gaming': 'ゲーミング',
        'Monitors': 'モニター', 'Headphones': 'ヘッドフォン', 'Smart Home': 'スマートホーム',
        'Trending Products': 'トレンド商品', 'Add to Cart': 'カートに追加',
        'Secure Payments': '安全な支払い', 'Fast Delivery': '高速配送',
        '24/7 Support': '24時間サポート', 'Sell on Aveenix': 'Aveenixで販売する',
        'Start Selling': '販売を始める', 'Compare Products': '商品比較',
        'Back to Home': 'ホームに戻る', 'Total Value': '合計価値',
        'In Stock': '在庫あり', 'On Sale': 'セール中',
        'Add All to Cart': 'すべてカートに追加', 'Clear Comparison': '比較をクリア',
        '0 items': '0 件', 'Add Products': '商品を追加',
        'My Favourites': 'マイお気に入り', 'All Items': 'すべてのアイテム',
        'List View': 'リスト表示', 'Total Favourites': 'お気に入り合計',
        'Clear Favourites': 'お気に入りをクリア', 'No favourites yet': 'まだお気に入りがありません',
        'Start Shopping': 'ショッピングを始める', 'My Wishlist': 'マイウィッシュリスト',
        'Clear Wishlist': 'ウィッシュリストをクリア', 'Your wishlist is empty': 'ウィッシュリストは空です',
        'Contact Us': 'お問い合わせ', 'Location': '所在地', 'Business Hours': '営業時間',
        'Send A Message': 'メッセージを送る', 'Free Consultancy': '無料相談',
        'Notifications': '通知', 'Mark All Read': 'すべて既読にする',
        'All': 'すべて', 'Orders': '注文', 'No notifications': '通知なし',
        'All Categories': 'すべてのカテゴリー', 'Add to favourite': 'お気に入りに追加',
        'Add to Compare': '比較に追加', 'My Account': 'マイアカウント',
        'Dark': 'ダーク', 'Sale': 'セール', 'Compare': '比較',
        'Cart': 'カート', 'Shop': 'ショップ', 'Home': 'ホーム',
        'Log Out': 'ログアウト',
        'products': '商品',
        'Recent Searches': '最近の検索',
        'Trending Searches': 'トレンド検索',
        'Customer Service': 'カスタマーサービス',
        'Information': '情報',
        'Account': 'アカウント',
        'Support': 'サポート',
        'Legal': '法的情報',
        'Settings': '設定',
        'Website': 'ウェブサイト',
        'Color': 'カラー',
        'Summer Electronics': '夏の電子機器',
        'For You': 'あなたへ',
        'Best Sellers': 'ベストセラー',
        'New Arrivals': '新着商品',
        'Contact': 'お問い合わせ',
        'Notifications': '通知',
        'Shop by Category': 'カテゴリーで探す',
        'Get the latest gadgets at unbeatable prices': '最新のガジェットをお得な価格で',
        'Fashion Week Special': 'ファッションウィーク特集',
        'Discover the latest trends in fashion': '最新のファッショントレンドを発見',
        'Beautiful furniture and decor for every room': 'すべての部屋に美しい家具と装飾',
        'Transform Your Space': '空間を変える',
        'Aveenix Express': 'Aveenix エクスプレス',
        'Regional Delivery Centers': '地域配送センター',
        'Products to Compare': '比較する商品',
        'Compare features, pricing, and specifications side-by-side': '機能・価格・仕様を並べて比較',
        'Start Comparing Products': '商品の比較を始める',
        'Add to favourites': 'お気に入りに追加',
        'Add to wishlist': 'ウィッシュリストに追加',
        'Added to wishlist': 'ウィッシュリストに追加しました',
        'Total Wishlist': 'ウィッシュリスト合計',
        'Toggle View': '表示切替',
        'Wishlist': 'ウィッシュリスト',
        'Favourites': 'お気に入り',
        'Categories': 'カテゴリー',
        'Name*': '名前*',
        'Email Address*': 'メールアドレス*',
        'Phone Number': '電話番号',
        'Your message...*': 'メッセージ...*',
        'Stay updated with order status, promotions, and important updates': '注文状況・プロモーション・重要な更新情報を受け取る',
        'Items you frequently purchase or access': 'よく購入・アクセスする商品',
        'Save items for later and track price changes': '後で買う商品を保存し価格変動を追跡',
        'Search items on Aveenix…': 'Aveenixで商品を検索…',
        'Color Theme': 'カラーテーマ',
        'Popular': '人気',
        'Extended Palette': '拡張パレット',
        'Contact support team': 'サポートチームに連絡',
        'Monday – Sunday: 06:00 – 18:00': '月曜～日曜: 06:00 – 18:00',
        'Public Holidays – Closed': '祝祭日 – 休業',
        'Login': 'ログイン',
        'Default': 'デフォルト',
        'Yellow': '黄色', 'Blue': '青', 'Green': '緑', 'Purple': '紫',
        'Red': '赤', 'Orange': 'オレンジ', 'Teal': 'ティール', 'Indigo': 'インディゴ',
        'Pink': 'ピンク', 'Lime': 'ライム', 'Cyan': 'シアン', 'Amber': 'アンバー',
        'Emerald': 'エメラルド', 'Violet': 'バイオレット', 'Rose': 'ローズ',
        'Sky': 'スカイ', 'Fuchsia': 'フクシア', 'Slate': 'スレート',
        'Browse all product categories': 'すべての商品カテゴリーを見る',
        'Shop Now': '今すぐ購入',
        'Explore': '探索',
        'Browse': 'ブラウズ',
        'View All': 'すべて見る',
        'Why Choose Aveenix?': 'なぜAveenixを選ぶのか？',
        'Secure Payments': '安全な支払い',
        'Safe and secure payment methods guaranteed.': '安全な決済方法を保証。',
        'Fast Delivery': '高速配送',
        'Current shipping at supreme delivery speeds.': '最高速度での配送。',
        'Hassle Free Returns': '簡単返品',
        'Simple and easy return policy for all products.': '全商品のシンプルな返品ポリシー。',
        '24/7 Support': '24時間サポート',
        'Round-the-clock customer support team.': '24時間対応カスタマーサポート。',
        'Sell on Aveenix': 'Aveenixで販売する',
        'Reach millions of customers by becoming a seller on AVEENIX': 'AVEENIXの販売者になり、数百万の顧客にリーチ',
        'Compare Products': '商品比較',
        'Back to Home': 'ホームに戻る',
        'Total Value': '合計価値',
        'In Stock': '在庫あり',
        'On Sale': 'セール中',
        'Add All to Cart': 'すべてカートに追加',
        'Clear Comparison': '比較をクリア',
        '0 items': '0 件',
        'Add Products': '商品を追加',
        'My Favourites': 'マイお気に入り',
        'All Items': 'すべてのアイテム',
        'Total Favourites': 'お気に入り合計',
        'Clear Favourites': 'お気に入りをクリア',
        'No favourites yet': 'まだお気に入りがありません',
        'Add products to your favourites by clicking the heart icon on product cards': '商品カードのハートアイコンをクリック',
        'Start Shopping': 'ショッピングを始める',
        'My Wishlist': 'マイウィッシュリスト',
        'Clear Wishlist': 'ウィッシュリストをクリア',
        'Your wishlist is empty': 'ウィッシュリストは空です',
        'Add products to your wishlist by clicking the star icon on product cards': '商品カードのスターアイコンをクリック',
        'Contact Us': 'お問い合わせ',
        'Location': '所在地',
        'Business Hours': '営業時間',
        'Send A Message': 'メッセージを送る',
        'Free Consultancy': '無料相談',
        'Filters': 'フィルター',
        'All': 'すべて',
        'Unread': '未読',
        'Orders': '注文',
        'Promotions': 'プロモーション',
        'Inventory': '在庫',
        'No notifications': '通知なし',
        'All Categories': 'すべてのカテゴリー',
        'Add to favourite': 'お気に入りに追加',
        'Add to Compare': '比較に追加',
        'View All Categories →': 'すべてのカテゴリーを見る →',
        'Get ': '獲得 ',
        '$20 OFF': '20ドル割引',
        ' your first order!': '初回注文！',
        'Enter your email': 'メールアドレスを入力',
        'Get $20 OFF': '20ドル割引を获得',
        'Country': '国',
        'Language': '言語',
        'Currency': '通貨',
        'Dark Mode': 'ダークモード',
        'POPULAR': '人気',
        'EXTENDED PALETTE': '拡張パレット',
        'Download on App Store': 'App Storeでダウンロード',
        'Get it on Google Play': 'Google Playで入手',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. 全著作権所有。',
        'Privacy Policy': 'プライバシーポリシー',
        'Cookie Policy': 'Cookieポリシー',
        'Contact Support': 'サポートに連絡',
        'Search products, brands, categories…': '商品・ブランド・カテゴリーを検索…',
        'Contact us': 'お問い合わせ',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "ご質問やサポートが必要ですか？お気軽にご連絡ください！Aveenixでは、お客様の満足を最優先に考えています。ご注文に関するお問い合わせ、サイトのご利用方法、または単にご連絡を取りたい場合など、専任サポートチームがいつでもお手伝いします。",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "下記のお問い合わせフォームからご連絡いただければ、迅速かつ丁寧に対応いたします。Aveenixで快適なショッピング体験をお楽しみください。私たちはあなたのオンラインショッピングを特別なものにするため全力を尽くしています。",
        'Site Us': '会社概要',
        'FAQs': 'よくある質問',
        'Order Tracking': '注文追跡',
        'Features': '機能',
        'Partners': 'パートナー',
        'Shipping Policy': '配送ポリシー',
        'Services': 'サービス',
        'Connect Aveenix': 'Aveenixに接続',
        'Registration': '登録',
        'Career Policy': 'キャリアポリシー',
        'Terms of Use': '利用規約',
        'TV & Video': 'TV・映像',
        'Cameras': 'カメラ',
        'Toggle dark mode': 'ダークモード切替',
        'Search': '検索',
        '✕ Clear All': '✕ すべてクリア',
        '0 of 0 notifications': '0件中0件の通知',
        "You're all caught up!": '全て確認済みです！',
        'New Arrivals': '新着商品',
        'Laptop': 'ノートパソコン',
        'Smartphone': 'スマートフォン',
        'Smart TV': 'スマートTV',
        'Tablet': 'タブレット',
        'Camera': 'カメラ',
        'Watch': '時計',
    },
    'pt': {
        'Up to 70% Off': 'Até 70% de desconto',
        'Shop Now': 'Comprar agora', 'New Arrivals': 'Novidades', 'Explore': 'Explorar',
        'Browse': 'Navegar', 'Previous': 'Anterior', 'Next': 'Próximo',
        'For You': 'Para você', 'Best Sellers': 'Mais vendidos', 'View All': 'Ver tudo',
        'Laptops': 'Notebooks', 'Mobile': 'Mobile', 'Gaming': 'Games',
        'Monitors': 'Monitores', 'Headphones': 'Fones de ouvido', 'Smart Home': 'Casa inteligente',
        'Trending Products': 'Produtos em alta', 'Add to Cart': 'Adicionar ao carrinho',
        'Secure Payments': 'Pagamentos seguros', 'Fast Delivery': 'Entrega rápida',
        'Hassle Free Returns': 'Devoluções sem complicações', '24/7 Support': 'Suporte 24/7',
        'Sell on Aveenix': 'Vender na Aveenix', 'Start Selling': 'Começar a vender',
        'Compare Products': 'Comparar produtos', 'Back to Home': 'Voltar ao início',
        'Total Value': 'Valor total', 'In Stock': 'Em estoque', 'On Sale': 'Em promoção',
        'Add All to Cart': 'Adicionar tudo ao carrinho', 'Clear Comparison': 'Limpar comparação',
        '0 items': '0 itens', 'Add Products': 'Adicionar produtos',
        'My Favourites': 'Meus favoritos', 'All Items': 'Todos os itens',
        'List View': 'Visualização em lista', 'Total Favourites': 'Total de favoritos',
        'Clear Favourites': 'Limpar favoritos', 'No favourites yet': 'Nenhum favorito ainda',
        'Start Shopping': 'Começar a comprar', 'My Wishlist': 'Minha lista de desejos',
        'Clear Wishlist': 'Limpar lista de desejos', 'Your wishlist is empty': 'Sua lista de desejos está vazia',
        'Contact Us': 'Entre em contato', 'Location': 'Localização', 'Business Hours': 'Horário de funcionamento',
        'Send A Message': 'Enviar uma mensagem', 'Free Consultancy': 'Consultoria gratuita',
        'Notifications': 'Notificações', 'Mark All Read': 'Marcar tudo como lido',
        'All': 'Todos', 'Orders': 'Pedidos', 'No notifications': 'Sem notificações',
        'All Categories': 'Todas as categorias', 'Add to favourite': 'Adicionar aos favoritos',
        'Add to Compare': 'Adicionar à comparação', 'My Account': 'Minha conta',
        'Dark': 'Escuro', 'Sale': 'Promoção', 'Compare': 'Comparar',
        'Cart': 'Carrinho', 'Shop': 'Loja', 'Home': 'Início',
        'Log Out': 'Sair',
        'products': 'produtos',
        'Recent Searches': 'Pesquisas recentes',
        'Trending Searches': 'Pesquisas em alta',
        'Customer Service': 'Atendimento ao cliente',
        'Information': 'Informações',
        'Account': 'Conta',
        'Support': 'Suporte',
        'Legal': 'Legal',
        'Settings': 'Configurações',
        'Website': 'Site',
        'Color': 'Cor',
        'Summer Electronics': 'Eletrônicos de verão',
        'For You': 'Para você',
        'Best Sellers': 'Mais vendidos',
        'New Arrivals': 'Novidades',
        'Contact': 'Contato',
        'Notifications': 'Notificações',
        'Shop by Category': 'Comprar por categoria',
        'Get the latest gadgets at unbeatable prices': 'Obtenha os gadgets mais recentes por preços imbatíveis',
        'Fashion Week Special': 'Especial Semana da Moda',
        'Discover the latest trends in fashion': 'Descubra as últimas tendências da moda',
        'Beautiful furniture and decor for every room': 'Belos móveis e decoração para cada ambiente',
        'Transform Your Space': 'Transforme seu espaço',
        'Aveenix Express': 'Aveenix Express',
        'Regional Delivery Centers': 'Centros de entrega regionais',
        'Products to Compare': 'Produtos a comparar',
        'Compare features, pricing, and specifications side-by-side': 'Compare recursos, preços e especificações lado a lado',
        'Start Comparing Products': 'Começar a comparar produtos',
        'Add to favourites': 'Adicionar aos favoritos',
        'Add to wishlist': 'Adicionar à lista de desejos',
        'Added to wishlist': 'Adicionado à lista de desejos',
        'Total Wishlist': 'Total da lista de desejos',
        'Toggle View': 'Alternar visualização',
        'Wishlist': 'Lista de desejos',
        'Favourites': 'Favoritos',
        'Categories': 'Categorias',
        'Name*': 'Nome*',
        'Email Address*': 'Endereço de e-mail*',
        'Phone Number': 'Número de telefone',
        'Your message...*': 'Sua mensagem...*',
        'Stay updated with order status, promotions, and important updates': 'Fique atualizado sobre pedidos, promoções e atualizações importantes',
        'Items you frequently purchase or access': 'Itens que você compra frequentemente',
        'Save items for later and track price changes': 'Salve itens para depois e acompanhe preços',
        'Search items on Aveenix…': 'Pesquisar itens na Aveenix…',
        'Color Theme': 'Tema de cor',
        'Popular': 'Popular',
        'Extended Palette': 'Paleta estendida',
        'Contact support team': 'Contatar equipe de suporte',
        'Monday – Sunday: 06:00 – 18:00': 'Segunda – Domingo: 06:00 – 18:00',
        'Public Holidays – Closed': 'Feriados – Fechado',
        'Login': 'Entrar',
        'Default': 'Padrão',
        'Yellow': 'Amarelo', 'Blue': 'Azul', 'Green': 'Verde', 'Purple': 'Roxo',
        'Red': 'Vermelho', 'Orange': 'Laranja', 'Teal': 'Verde-azulado', 'Indigo': 'Índigo',
        'Pink': 'Rosa', 'Lime': 'Lima', 'Cyan': 'Ciano', 'Amber': 'Âmbar',
        'Emerald': 'Esmeralda', 'Violet': 'Violeta', 'Rose': 'Rosa escuro',
        'Sky': 'Céu', 'Fuchsia': 'Fúcsia', 'Slate': 'Ardósia',
        'Browse all product categories': 'Explorar todas as categorias de produtos',
        'Shop Now': 'Comprar agora',
        'Explore': 'Explorar',
        'Browse': 'Navegar',
        'View All': 'Ver tudo',
        'Why Choose Aveenix?': 'Por que escolher a Aveenix?',
        'Secure Payments': 'Pagamentos seguros',
        'Safe and secure payment methods guaranteed.': 'Métodos de pagamento seguros e confiáveis garantidos.',
        'Fast Delivery': 'Entrega rápida',
        'Current shipping at supreme delivery speeds.': 'Envio com velocidades de entrega supremas.',
        'Simple and easy return policy for all products.': 'Política de devolução simples e fácil para todos os produtos.',
        'Round-the-clock customer support team.': 'Equipe de suporte ao cliente disponível 24 horas.',
        'Sell on Aveenix': 'Vender na Aveenix',
        'Reach millions of customers by becoming a seller on AVEENIX': 'Alcance milhões de clientes tornando-se um vendedor na AVEENIX',
        'Add to favourite': 'Adicionar aos favoritos',
        'Add to Compare': 'Adicionar à comparação',
        'Add products to your favourites by clicking the heart icon on product cards': 'Clique no ícone de coração nos cartões de produto',
        'Add products to your wishlist by clicking the star icon on product cards': 'Clique no ícone de estrela nos cartões de produto',
        'Filters': 'Filtros',
        'Unread': 'Não lido',
        'Promotions': 'Promoções',
        'Inventory': 'Inventário',
        'View All Categories →': 'Ver todas as categorias →',
        'Get ': 'Ganhe ',
        '$20 OFF': 'R$20 de desconto',
        ' your first order!': ' no seu primeiro pedido!',
        'Enter your email': 'Digite seu e-mail',
        'Get $20 OFF': 'Ganhe R$20 de desconto',
        'Country': 'País',
        'Language': 'Idioma',
        'Currency': 'Moeda',
        'Dark Mode': 'Modo escuro',
        'POPULAR': 'POPULAR',
        'EXTENDED PALETTE': 'PALETA ESTENDIDA',
        'Download on App Store': 'Baixar na App Store',
        'Get it on Google Play': 'Disponível no Google Play',
        '© 2025 AVEENIX. All rights reserved.': '© 2025 AVEENIX. Todos os direitos reservados.',
        'Privacy Policy': 'Política de privacidade',
        'Cookie Policy': 'Política de cookies',
        'Contact Support': 'Contatar suporte',
        'Search products, brands, categories…': 'Pesquisar produtos, marcas, categorias…',
        'Contact us': 'Entre em contato',
        "Got questions or need assistance? We're here to help! At Aveenix, your satisfaction is our top priority. Whether you have inquiries about your order, need help navigating our website, or simply want to connect, our dedicated support team is ready to assist you.": "Tem dúvidas ou precisa de ajuda? Estamos aqui para ajudar! Na Aveenix, sua satisfação é nossa prioridade máxima. Seja para dúvidas sobre seu pedido, ajuda para navegar em nosso site ou apenas para entrar em contato, nossa equipe de suporte dedicada está pronta para atendê-lo.",
        "Reach out through the contact form below for a swift and helpful response. Enjoy a seamless shopping experience with Aveenix, where we're committed to making your online journey exceptional. Shop with confidence knowing we're just a message away!": "Entre em contato pelo formulário abaixo para uma resposta rápida e útil. Aproveite uma experiência de compra perfeita com a Aveenix, onde nos comprometemos a tornar sua jornada online excepcional. Compre com confiança sabendo que estamos a apenas uma mensagem de distância!",
        'Site Us': 'Sobre nós',
        'FAQs': 'Perguntas frequentes',
        'Order Tracking': 'Rastreamento de pedido',
        'Features': 'Recursos',
        'Partners': 'Parceiros',
        'Shipping Policy': 'Política de envio',
        'Services': 'Serviços',
        'Connect Aveenix': 'Conectar Aveenix',
        'Registration': 'Cadastro',
        'Career Policy': 'Política de carreira',
        'Terms of Use': 'Termos de uso',
        'TV & Video': 'TV e Vídeo',
        'Cameras': 'Câmeras',
        'Toggle dark mode': 'Alternar modo escuro',
        'Search': 'Pesquisar',
        '✕ Clear All': '✕ Limpar tudo',
        '0 of 0 notifications': '0 de 0 notificações',
        "You're all caught up!": 'Você está em dia!',
        'New Arrivals': 'Novidades',
        'Laptop': 'Notebook',
        'Smartphone': 'Smartphone',
        'Smart TV': 'Smart TV',
        'Tablet': 'Tablet',
        'Camera': 'Câmera',
        'Watch': 'Relógio',
    },
}

LANG_META = {
    'zh_CN': ('Chinese Simplified', 'nplurals=1; plural=0;'),
    'fr':    ('French',   'nplurals=2; plural=(n > 1);'),
    'de':    ('German',   'nplurals=2; plural=(n != 1);'),
    'it':    ('Italian',  'nplurals=2; plural=(n != 1);'),
    'ja':    ('Japanese', 'nplurals=1; plural=0;'),
    'pt':    ('Portuguese', 'nplurals=2; plural=(n != 1);'),
    'es':    ('Spanish',  'nplurals=2; plural=(n != 1);'),
}

def translate_text(text, translations):
    """Translate a plain text string, preserving surrounding whitespace."""
    stripped = text.strip()
    if stripped and stripped in translations:
        # Preserve leading/trailing whitespace from original
        lead = text[:len(text) - len(text.lstrip())]
        trail = text[len(text.rstrip()):]
        return lead + translations[stripped] + trail
    return None

def translate_fragment(msgid, translations):
    """Given an XML-fragment msgid, return translated msgstr or '' if nothing to translate."""
    if not ('<' in msgid):
        # plain text
        result = translate_text(msgid, translations)
        return result if result else ''

    try:
        root = etree.fromstring(f'<div>{msgid}</div>')
    except etree.XMLSyntaxError:
        return ''

    changed = [False]

    def translate_node(node):
        if isinstance(node.tag, str):
            if node.text:
                t = translate_text(node.text, translations)
                if t is not None:
                    node.text = t
                    changed[0] = True
            if node.tail:
                t = translate_text(node.tail, translations)
                if t is not None:
                    node.tail = t
                    changed[0] = True
            for attr in TRANSLATED_ATTRS:
                val = node.get(attr, '')
                if val.strip() in translations:
                    node.set(attr, translations[val.strip()])
                    changed[0] = True
            for child in node:
                translate_node(child)
        else:
            if node.tail:
                t = translate_text(node.tail, translations)
                if t is not None:
                    node.tail = t
                    changed[0] = True

    translate_node(root)

    if not changed[0]:
        return ''

    result = serialize_fragment(root)
    return result

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def write_po(lang, lang_name, plural_forms, translations):
    lines = []
    lines.append(f'# {lang_name} translation for aveenix_website')
    lines.append('# Copyright (C) 2024 Aveenix')
    lines.append('#')
    lines.append('msgid ""')
    lines.append('msgstr ""')
    lines.append('"Project-Id-Version: Odoo Server 19.0\\n"')
    lines.append('"Report-Msgid-Bugs-To: \\n"')
    lines.append('"POT-Creation-Date: 2024-01-01 00:00+0000\\n"')
    lines.append('"PO-Revision-Date: 2024-01-01 00:00+0000\\n"')
    lines.append('"Last-Translator: \\n"')
    lines.append(f'"Language-Team: {lang_name}\\n"')
    lines.append(f'"Language: {lang}\\n"')
    lines.append('"MIME-Version: 1.0\\n"')
    lines.append('"Content-Type: text/plain; charset=UTF-8\\n"')
    lines.append('"Content-Transfer-Encoding: 8bit\\n"')
    lines.append(f'"Plural-Forms: {plural_forms}\\n"')
    lines.append('')

    covered = 0
    for msgid, xmlids in strings_data:
        msgstr = translate_fragment(msgid, translations)
        lines.append(f'#. module: {MODULE}')
        for xmlid in xmlids:
            lines.append(f'#: model_terms:ir.ui.view,arch_db:{xmlid}')
        lines.append(f'msgid "{esc(msgid)}"')
        lines.append(f'msgstr "{esc(msgstr)}"')
        lines.append('')
        if msgstr:
            covered += 1

    path = os.path.join(I18N_DIR, f'{lang}.po')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'Written: {lang}.po  ({covered}/{len(strings_data)} translated)')

for lang, (lang_name, plural_forms) in LANG_META.items():
    write_po(lang, lang_name, plural_forms, TRANSLATIONS.get(lang, {}))

print('Done.')
