{
    'name': 'Aveenix Rewards',
    'version': '19.0.1.0.1',
    'category': 'Sales',
    'summary': 'Margin-based reward engine with ewallet integration',
    'author': 'Anantam Innovision Private Limited',
    'website': 'https://anantaminnovision.com/',
    'depends': [
        'sale_management',
        'account',
        'loyalty',
        'sale_loyalty',
        'website_sale_loyalty',
        'base_setup',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/reward_sequence_data.xml',
        'data/loyalty_ewallet_data.xml',
        'data/ir_cron_data.xml',
        'views/payment_gateway_config_views.xml',
        'views/reward_config_views.xml',
        'views/reward_record_views.xml',
        'views/reward_redemption_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/sale_order_views.xml',
        'views/menus.xml',
        'views/website_templates.xml',
        'wizard/bulk_approve_views.xml',
        'wizard/reject_redemption_views.xml',
    ],
    'images': ['static/description/icon.png', 'static/description/icon_hi.png'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
